### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by KeKsBoTer** [niklaskorz/nklang#1]
What did I do?
 ```bash
$ go get github.com/niklaskorz/nklang 
$ go build go build niklaskorz.de/nklang/cmd/nklg
```

Error:
`cmd/nklg/main.go:31:13: p.Execute undefined (type *ast.Program has no field or method Execute)`

**Comment by niklaskorz** [comment]
Should work now.

```sh
go get github.com/niklaskorz/nklang
cd $GOPATH/github.com/niklaskorz/nklang
go run cmd/nklg/main.go
```
or

```sh
go install github.com/niklaskorz/nklang/cmd/nklg
```

and execute `nklg`. This currently just runs `example.nk` in the current working directory.

**Comment by niklaskorz** [comment]
You can now execute arbitrary files with `nklg <file>`, e.g. `nklg example.nk`.
